services:
  ftp-server:
    container_name: test-ftp-server
    environment:
      - PUBLIC_IP=127.0.0.1
      - FTP_PASS=123
      - FTP_USER=user
    image: garethflowers/ftp-server
    ports:
      - "20-21:20-21/tcp"
      - "40000-40009:40000-40009/tcp" # For passive mode
    volumes:
      - "/data:/home/user"
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    command: user:123:::upload